version: "3.8"

services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - postgres
    ports:
      - 5000:5000
    environment:
      DB_NAME: postgres
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: 5432

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    networks:
      - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:


networks:
  postgres:
