version: "3.8"

services:
  server:
    image: python-react-time-tracker-server:latest
    networks:
      - postgres
    ports:
      - 5055:5000
    environment:
      DB_NAME: postgres
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: 5432
      FLASK_SESSION_SECRET: supersecret

  postgres:
    image: postgres:alpine3.19
    restart: always
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    networks:
      - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:


networks:
  postgres:
