version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    networks:
      - postgres
    ports:
      - 5001:5000
    environment:
      DB_NAME: postgres
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: 5432

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:

networks:
  postgres:
