name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME_TAG: pyre-time:$GITHUB_SHA

jobs:

  build:

    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME_TAG
        docker tag $IMAGE_NAME_TAG ${{ secrets.DOCKER_REGISTRY_ADDRESS }}/$IMAGE_NAME_TAG
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY_ADDRESS }}

    - name: Deploy to CapRover
      uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
      with:
          server: ${{ secrets.CAPROVER_HOST }}
          app: ${{ secrets.CAPROVER_APP }}
          token: '${{ secrets.CAPROVER_APP_TOKEN }}'
          image: $IMAGE_NAME_TAG
