name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag pyre-time:${{ git.sha }}
        docker tag pyre-time:${{ git.sha }} ${{ secrets.DOCKER_REGISTRY_ADDRESS }}/pyre-time:${{ git.sha }}
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY_ADDRESS }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_REGISTRY_ADDRESS }}/pyre-time:${{ git.sha }}
